# fly.toml app configuration file generated for mailing-list-api on 2023-11-18T23:23:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mailing-list-api"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
